"use client";

import "./assets/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProvider } from "./context/store";
import StyledJsxRegistry from "./registry";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <StyledJsxRegistry>
            <html lang="en">
                <body>
                    <QueryClientProvider client={queryClient}>
                        <AppProvider>{children}</AppProvider>
                    </QueryClientProvider>
                </body>
            </html>
        </StyledJsxRegistry>
    );
}
