import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProvider } from "./context/store";
import StyledJsxRegistry from "./registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <StyledJsxRegistry>
            <html lang="en">
                <body>
                    <AppProvider>{children}</AppProvider>
                </body>
            </html>
        </StyledJsxRegistry>
    );
}
